# Generated by Django 5.0.4 on 2024-05-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_five', '0004_alter_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, null=True, verbose_name='contact')),
                ('contact_info', models.TextField(max_length=50, null=True, verbose_name='contact_info')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
