# Generated by Django 5.0.4 on 2024-05-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_five', '0006_rename_notes_reviewmodel_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
